package main.View;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class MainWindow extends JFrame {

    private JPanel panel1;
    private JToolBar toolbar;
    private JButton fileButton;
    private JButton saveButton;
    private JScrollBar bottomScrollBar;
    private JScrollBar sideScrollBar;
    private JPanel drawField;
    private JPanel editField;
    private JButton deceasedButton;
    private JButton addNewChildButton;
    private JButton modifyButton;
    private JPanel detailsField;
    private JTextField nameTextField;
    private JTextField birthDateTextField;
    private JTextField birthPlaceTextField;
    private JTextField deathDateTextField;
    private JTextField deathPlaceTextField;
    private JLabel nameLabel;
    private JLabel birthDateLabel;
    private JLabel birthPlaceLabel;
    private JLabel deathDateLabel;
    private JLabel deathPlaceLabel;

    public MainWindow() {
        $$$setupUI$$$();
        this.setSize(800, 800);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.setVisible(true);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        panel1 = new JPanel();
        this.add(panel1);
        panel1.setLayout(new BorderLayout(0, 0));

        drawField = new JPanel();
        drawField.setLayout(new GridLayoutManager(5, 5, new Insets(0, 0, 0, 0), -1, -1, true, true));  // params( magasság,szélesség,borders of this container,-,-)
        panel1.add(drawField, BorderLayout.CENTER);
        JLabel testLabel1 = new JLabel();
        JLabel testLabel2 = new JLabel();
        JLabel testLabel3 = new JLabel();
        JLabel testLabel4 = new JLabel();
        testLabel1.setText("kurva");
        testLabel2.setText("kurva");
        testLabel3.setText("kurva");
        testLabel4.setText("kurva");
        drawField.add(testLabel1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        drawField.add(testLabel2, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        drawField.add(testLabel3, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        drawField.add(testLabel4, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
/*

        drawField.setLayout(new BorderLayout());

        JLabel label = new JLabel();
        label.setText("Kurva");
        drawField.add(label, BorderLayout.CENTER);
        panel1.add(drawField, BorderLayout.CENTER);

    */
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setBackground(new Color(-12828863));
        panel1.setEnabled(true);
        toolbar = new JToolBar();
        toolbar.setFloatable(false);
        panel1.add(toolbar, BorderLayout.NORTH);
        fileButton = new JButton();
        fileButton.setText("File");
        toolbar.add(fileButton);
        final JToolBar.Separator toolBar$Separator1 = new JToolBar.Separator();
        toolbar.add(toolBar$Separator1);
        saveButton = new JButton();
        saveButton.setText("Save");
        toolbar.add(saveButton);
        bottomScrollBar = new JScrollBar();
        bottomScrollBar.setOrientation(0);
        panel1.add(bottomScrollBar, BorderLayout.SOUTH);
        sideScrollBar = new JScrollBar();
        panel1.add(sideScrollBar, BorderLayout.EAST);
        editField = new JPanel();
        editField.setLayout(new BorderLayout(0, 0));
        panel1.add(editField, BorderLayout.WEST);
        editField.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        final JToolBar toolBar1 = new JToolBar();
        toolBar1.setFloatable(false);
        editField.add(toolBar1, BorderLayout.NORTH);
        addNewChildButton = new JButton();
        addNewChildButton.setText("Add New Child");
        toolBar1.add(addNewChildButton);
        final JToolBar.Separator toolBar$Separator2 = new JToolBar.Separator();
        toolBar1.add(toolBar$Separator2);
        deceasedButton = new JButton();
        deceasedButton.setText("Deceased");
        toolBar1.add(deceasedButton);
        final JToolBar.Separator toolBar$Separator3 = new JToolBar.Separator();
        toolBar1.add(toolBar$Separator3);
        modifyButton = new JButton();
        modifyButton.setText("Modify");
        toolBar1.add(modifyButton);
        detailsField = new JPanel();
        detailsField.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        editField.add(detailsField, BorderLayout.CENTER);
        nameLabel = new JLabel();
        nameLabel.setText("Name");
        detailsField.add(nameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        birthDateLabel = new JLabel();
        birthDateLabel.setText("Birth Date");
        detailsField.add(birthDateLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        birthPlaceLabel = new JLabel();
        birthPlaceLabel.setText("Birth Place");
        detailsField.add(birthPlaceLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        deathDateLabel = new JLabel();
        deathDateLabel.setText("Death Date");
        detailsField.add(deathDateLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nameTextField = new JTextField();
        detailsField.add(nameTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        birthDateTextField = new JTextField();
        detailsField.add(birthDateTextField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        birthPlaceTextField = new JTextField();
        detailsField.add(birthPlaceTextField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        deathDateTextField = new JTextField();
        detailsField.add(deathDateTextField, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        deathPlaceLabel = new JLabel();
        deathPlaceLabel.setText("Death Place");
        detailsField.add(deathPlaceLabel, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        deathPlaceTextField = new JTextField();
        detailsField.add(deathPlaceTextField, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        panel1.add(drawField, BorderLayout.CENTER);
        nameLabel.setLabelFor(nameTextField);
        birthDateLabel.setLabelFor(birthDateTextField);
        birthPlaceLabel.setLabelFor(birthPlaceTextField);
        deathDateLabel.setLabelFor(deathDateTextField);
        deathPlaceLabel.setLabelFor(deathPlaceTextField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
